In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# <font color = 2B46E0> 원핫인코딩 & fold

In [40]:
def find_max_cat_y(df):
    max_y_values = []
    for i in df['label']:
        max_y_values.append(i)
    max_y = max(max_y_values)
    return(max_y)



# 원핫인코딩 하기 전에 설명변수들의 범주의 최댓값 찾기
def find_max_cat_X(df, col):
    df.columns = col
    max_values = []
    for i in col.drop('label'):
        max_values.append(max(df[i]))
    max_x = int(max(max_values))
    return max_x, max_values


# 원핫인코딩
def get_dummies_max(df, col, max_x, max_values):
    df_dummy = pd.get_dummies(df, columns=col)
    idx =[]
    for c in df_dummy.columns:
        if 'label' in c:
            idx.append(c)
    for j in range(1, len(max_values)+1):
        for k in range(1, max_x+1):
            idx.append(f'X{j}_{k}')
            test = df_dummy.reindex(idx, axis=1, fill_value = 0)
    return test


In [55]:
df = pd.read_csv('breast-cancer-wisconsin_1.csv')
df

X1  X2  X3  X4  X5  X6  X7  X8  X9  label
0     5   1   1   1   2   1   3   1   1      0
1     5   4   4   5   7  10   3   2   1      0
2     3   1   1   1   2   2   3   1   1      0
3     6   8   8   1   3   4   3   7   1      0
4     4   1   1   3   2   1   3   1   1      0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
678   3   1   1   1   3   2   1   1   1      0
679   2   1   1   1   2   1   1   1   1      0
680   5  10  10   3   7   3   8  10   2      1
681   4   8   6   4   3   4  10   6   1      1
682   4   8   8   5   4   5  10   4   1      1

[683 rows x 10 columns]

In [56]:
df.shape[0]

683

In [57]:
df['label'] += 1
df

X1  X2  X3  X4  X5  X6  X7  X8  X9  label
0     5   1   1   1   2   1   3   1   1      1
1     5   4   4   5   7  10   3   2   1      1
2     3   1   1   1   2   2   3   1   1      1
3     6   8   8   1   3   4   3   7   1      1
4     4   1   1   3   2   1   3   1   1      1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
678   3   1   1   1   3   2   1   1   1      1
679   2   1   1   1   2   1   1   1   1      1
680   5  10  10   3   7   3   8  10   2      2
681   4   8   6   4   3   4  10   6   1      2
682   4   8   8   5   4   5  10   4   1      2

[683 rows x 10 columns]

In [58]:
col = df.columns
for i in range(1, len(col)):
    x = df['X'+str(i)].unique()
    x.sort()
#     print(len(x))
    print(x)
x = df['label'].unique()
x.sort()
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8 10]
[1 2]


In [45]:
# 데이터 불러와서
# df = pd.read_csv('Musk_2.csv')

# int형을 category로 만들어서 category값을 1부터 순서대로 바꿔주기
for i in range(1, len(col)):
    idx = 'X'+str(i)
    df[idx] = df[idx].astype('category')
    a = np.sort(df[idx].unique())
#     print(a)
    for j in range(len(a)):
        a[j] = j+1
    df[idx].values.categories = a

# label값에 1씩 더해주기(0 -> 1)
# df['class'] = df['class'] + 1

# 확인하기
for i in range(1, len(col)):
    idx = 'X'+str(i)
    print(df[idx].values.categories)
    print()

# df.to_csv('Musk_2_1.csv')

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')



In [46]:
df

X1  X2  X3 X4 X5  X6  X7  X8 X9  label
0    5   1   1  1  2   1   3   1  1      1
1    5   4   4  5  7  10   3   2  1      1
2    3   1   1  1  2   2   3   1  1      1
3    6   8   8  1  3   4   3   7  1      1
4    4   1   1  3  2   1   3   1  1      1
..  ..  ..  .. .. ..  ..  ..  .. ..    ...
678  3   1   1  1  3   2   1   1  1      1
679  2   1   1  1  2   1   1   1  1      1
680  5  10  10  3  7   3   8  10  2      2
681  4   8   6  4  3   4  10   6  1      2
682  4   8   8  5  4   5  10   4  1      2

[683 rows x 10 columns]

In [47]:
df = df.astype('int64')
# df.info()

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      683 non-null    int64
 1   X2      683 non-null    int64
 2   X3      683 non-null    int64
 3   X4      683 non-null    int64
 4   X5      683 non-null    int64
 5   X6      683 non-null    int64
 6   X7      683 non-null    int64
 7   X8      683 non-null    int64
 8   X9      683 non-null    int64
 9   label   683 non-null    int64
dtypes: int64(10)
memory usage: 53.5 KB


In [49]:
col = df.columns
for i in range(1, len(col)):
    x = df['X'+str(i)].unique()
    x.sort()
#     print(len(x))
    print(x)
x = df['label'].unique()
x.sort()
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8 9]
[1 2]


In [118]:
df

X1  X2  X3  X4  X5  X6  X7  X8  X9  label
0     5   1   1   1   2   1   3   1   1      1
1     5   4   4   5   7  10   3   2   1      1
2     3   1   1   1   2   2   3   1   1      1
3     6   8   8   1   3   4   3   7   1      1
4     4   1   1   3   2   1   3   1   1      1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
678   3   1   1   1   3   2   1   1   1      1
679   2   1   1   1   2   1   1   1   1      1
680   5  10  10   3   7   3   8  10   2      2
681   4   8   6   4   3   4  10   6   1      2
682   4   8   8   5   4   5  10   4   1      2

[683 rows x 10 columns]

In [119]:
print(find_max_cat_y(df))

2


In [120]:
n, max_value = find_max_cat_X(df, col)
print(n)
print(max_value)

10
[10, 10, 10, 10, 10, 10, 10, 10, 10]


In [121]:
cancer = df.copy()
fold = pd.read_csv('fold.csv')
fold

ind  test_fold
0      0          1
1      1          0
2      2          1
3      3          1
4      4          1
..   ...        ...
678  678          0
679  679          1
680  680          0
681  681          1
682  682          0

[683 rows x 2 columns]

In [122]:
mer = pd.merge(cancer, fold, left_index=True, right_index=True, how='left')
mer = mer.drop('ind', axis=1)
mer

X1  X2  X3  X4  X5  X6  X7  X8  X9  label  test_fold
0     5   1   1   1   2   1   3   1   1      1          1
1     5   4   4   5   7  10   3   2   1      1          0
2     3   1   1   1   2   2   3   1   1      1          1
3     6   8   8   1   3   4   3   7   1      1          1
4     4   1   1   3   2   1   3   1   1      1          1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...        ...
678   3   1   1   1   3   2   1   1   1      1          0
679   2   1   1   1   2   1   1   1   1      1          1
680   5  10  10   3   7   3   8  10   2      2          0
681   4   8   6   4   3   4  10   6   1      2          1
682   4   8   8   5   4   5  10   4   1      2          0

[683 rows x 11 columns]

In [123]:
mer['test_fold'].unique()

array([1, 0, 2], dtype=int64)

In [124]:
f0 = (mer['test_fold'] == 0)
f1 = (mer['test_fold'] == 1)
f2 = (mer['test_fold'] == 2)

In [133]:
f0_train = mer[f1 | f2]
f0_train = f0_train.drop('test_fold', axis=1)
f0_test = mer[f0]
f0_test = f0_test.drop('test_fold', axis=1)

f1_train = mer[f0 | f2]
f1_train = f1_train.drop('test_fold', axis=1)
f1_test = mer[f1]
f1_test = f1_test.drop('test_fold', axis=1)

f2_train = mer[f1 | f0]
f2_train = f2_train.drop('test_fold', axis=1)
f2_test = mer[f2]
f2_test = f2_test.drop('test_fold', axis=1)

In [126]:
# f0_train = get_dummies_max(f0_train, col, n, max_value)
f0_test = get_dummies_max(f0_test, col, n, max_value)
# f1_train = get_dummies_max(f1_train, col, n, max_value)
f1_test = get_dummies_max(f1_test, col, n, max_value)
# f2_train = get_dummies_max(f2_train, col, n, max_value)
f2_test = get_dummies_max(f2_test, col, n, max_value)

In [134]:
f0_test

X1  X2  X3  X4  X5  X6  X7  X8  X9  label
1     5   4   4   5   7  10   3   2   1      1
6     1   1   1   1   2  10   3   1   1      1
8     2   1   1   1   2   1   1   1   5      1
10    1   1   1   1   1   1   3   1   1      1
12    5   3   3   3   2   3   4   4   1      2
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
665   5  10  10  10   4  10   5   6   3      2
675   5  10  10   5   4   5   4   4   1      2
678   3   1   1   1   3   2   1   1   1      1
680   5  10  10   3   7   3   8  10   2      2
682   4   8   8   5   4   5  10   4   1      2

[228 rows x 10 columns]

In [135]:
f0_train.columns

Index(['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'label'], dtype='object')

In [136]:
# f0_train.to_csv('BreastCancer_f0_train_no.csv', index=0)
f0_test.to_csv('BreastCancer_f0_test_one.csv', index=0)

# f1_train.to_csv('BreastCancer_f1_train_no.csv', index=0)
f1_test.to_csv('BreastCancer_f1_test_one.csv', index=0)

# f2_train.to_csv('BreastCancer_f2_train_no.csv', index=0)
f2_test.to_csv('BreastCancer_f2_test_one.csv', index=0)

In [117]:
f2_test[f2_test['label']==2]

X1  X2  X3  X4  X5  X6  X7  X8  X9  label
24    5   2   3   4   2   7   3   6   1      2
35   10  10  10   8   6   1   8   9   1      2
41    5   6   5   6  10   1   3   1   1      2
42   10  10  10   4   8   1   8  10   1      2
44    3   7   7   4   4   9   4   8   1      2
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
577  10   3   4   5   3  10   4   1   1      2
579   4   8   6   3   4  10   7   1   1      2
588   5   4   6   8   4   1   8  10   1      2
617   8   7   4   4   5   3   5  10   1      2
652   5   7   4   1   6   1   7  10   3      2

[84 rows x 10 columns]

In [60]:
f0_test = get_dummies_max(df, col, n, max_value)


In [105]:
f0_test

label_1  label_2  X1_1  X1_2  X1_3  X1_4  X1_5  X1_6  X1_7  X1_8  ...  \
1          1        0     0     0     0     0     1     0     0     0  ...   
6          1        0     1     0     0     0     0     0     0     0  ...   
8          1        0     0     1     0     0     0     0     0     0  ...   
10         1        0     1     0     0     0     0     0     0     0  ...   
12         0        1     0     0     0     0     1     0     0     0  ...   
..       ...      ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
665        0        1     0     0     0     0     1     0     0     0  ...   
675        0        1     0     0     0     0     1     0     0     0  ...   
678        1        0     0     0     1     0     0     0     0     0  ...   
680        0        1     0     0     0     0     1     0     0     0  ...   
682        0        1     0     0     0     1     0     0     0     0  ...   

     X9_1  X9_2  X9_3  X9_4  X9_5  X9_6  X9_7  X9_8  X9_9  X9_10  
1       1     0     0     0     0     0     0     0     0      0  
6       1     0     0     0     0     0     0     0     0      0  
8       0     0     0     0     1     0     0     0     0      0  
10      1     0     0     0     0     0     0     0     0      0  
12      1     0     0     0     0     0     0     0     0      0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  
665     0     0     1     0     0     0     0     0     0      0  
675     1     0     0     0     0     0     0     0     0      0  
678     1     0     0     0     0     0     0     0     0      0  
680     0     1     0     0     0     0     0     0     0      0  
682     1     0     0     0     0     0     0     0     0      0  

[228 rows x 92 columns]

In [63]:
f0_test.columns

Index(['label_1', 'label_2', 'X1_1', 'X1_2', 'X1_3', 'X1_4', 'X1_5', 'X1_6',
       'X1_7', 'X1_8', 'X1_9', 'X1_10', 'X2_1', 'X2_2', 'X2_3', 'X2_4', 'X2_5',
       'X2_6', 'X2_7', 'X2_8', 'X2_9', 'X2_10', 'X3_1', 'X3_2', 'X3_3', 'X3_4',
       'X3_5', 'X3_6', 'X3_7', 'X3_8', 'X3_9', 'X3_10', 'X4_1', 'X4_2', 'X4_3',
       'X4_4', 'X4_5', 'X4_6', 'X4_7', 'X4_8', 'X4_9', 'X4_10', 'X5_1', 'X5_2',
       'X5_3', 'X5_4', 'X5_5', 'X5_6', 'X5_7', 'X5_8', 'X5_9', 'X5_10', 'X6_1',
       'X6_2', 'X6_3', 'X6_4', 'X6_5', 'X6_6', 'X6_7', 'X6_8', 'X6_9', 'X6_10',
       'X7_1', 'X7_2', 'X7_3', 'X7_4', 'X7_5', 'X7_6', 'X7_7', 'X7_8', 'X7_9',
       'X7_10', 'X8_1', 'X8_2', 'X8_3', 'X8_4', 'X8_5', 'X8_6', 'X8_7', 'X8_8',
       'X8_9', 'X8_10', 'X9_1', 'X9_2', 'X9_3', 'X9_4', 'X9_5', 'X9_6', 'X9_7',
       'X9_8', 'X9_9', 'X9_10'],
      dtype='object')

In [68]:
f0_test['X9_10'].unique()

array([0, 1], dtype=uint8)

In [69]:
df

X1  X2  X3  X4  X5  X6  X7  X8  X9  label
0     5   1   1   1   2   1   3   1   1      1
1     5   4   4   5   7  10   3   2   1      1
2     3   1   1   1   2   2   3   1   1      1
3     6   8   8   1   3   4   3   7   1      1
4     4   1   1   3   2   1   3   1   1      1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
678   3   1   1   1   3   2   1   1   1      1
679   2   1   1   1   2   1   1   1   1      1
680   5  10  10   3   7   3   8  10   2      2
681   4   8   6   4   3   4  10   6   1      2
682   4   8   8   5   4   5  10   4   1      2

[683 rows x 10 columns]

In [70]:
df_1 = get_dummies_max(df, col, n, max_value)

In [71]:
df_1

label_1  label_2  X1_1  X1_2  X1_3  X1_4  X1_5  X1_6  X1_7  X1_8  ...  \
0          1        0     0     0     0     0     1     0     0     0  ...   
1          1        0     0     0     0     0     1     0     0     0  ...   
2          1        0     0     0     1     0     0     0     0     0  ...   
3          1        0     0     0     0     0     0     1     0     0  ...   
4          1        0     0     0     0     1     0     0     0     0  ...   
..       ...      ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
678        1        0     0     0     1     0     0     0     0     0  ...   
679        1        0     0     1     0     0     0     0     0     0  ...   
680        0        1     0     0     0     0     1     0     0     0  ...   
681        0        1     0     0     0     1     0     0     0     0  ...   
682        0        1     0     0     0     1     0     0     0     0  ...   

     X9_1  X9_2  X9_3  X9_4  X9_5  X9_6  X9_7  X9_8  X9_9  X9_10  
0       1     0     0     0     0     0     0     0     0      0  
1       1     0     0     0     0     0     0     0     0      0  
2       1     0     0     0     0     0     0     0     0      0  
3       1     0     0     0     0     0     0     0     0      0  
4       1     0     0     0     0     0     0     0     0      0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  
678     1     0     0     0     0     0     0     0     0      0  
679     1     0     0     0     0     0     0     0     0      0  
680     0     1     0     0     0     0     0     0     0      0  
681     1     0     0     0     0     0     0     0     0      0  
682     1     0     0     0     0     0     0     0     0      0  

[683 rows x 92 columns]

In [ ]:
from sklearn.model_selection import train_test_split

train_df, test_df= train_test_split(df, test_size=0.3, randome_state=0)

In [73]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3, shuffle=True, random_state=0)

# for train_index

In [74]:
kf

KFold(n_splits=3, random_state=0, shuffle=True)

In [78]:
for t,v in kf.split(df):
    print(v)

[  1   6   8  10  12  14  15  17  18  21  31  34  37  40  45  48  49  50
  52  55  62  64  66  68  71  75  76  77  78  79  85  90  92 101 103 109
 113 118 122 127 132 140 142 144 155 156 157 159 161 162 165 170 173 175
 178 181 187 188 190 193 194 196 200 202 204 205 210 214 215 222 230 231
 233 235 236 239 240 242 243 245 247 249 250 251 252 258 261 263 266 267
 268 271 278 279 283 285 293 294 299 301 303 306 310 312 313 315 316 317
 318 319 325 327 330 332 334 338 339 342 344 346 351 352 354 355 360 362
 365 366 369 378 380 386 392 395 397 402 403 406 408 413 420 426 427 428
 435 440 441 443 447 451 452 453 454 455 465 467 468 470 476 477 478 480
 481 482 489 490 491 494 497 498 499 500 503 504 505 506 513 517 518 521
 524 527 529 533 534 535 539 540 542 546 556 557 558 568 569 570 571 591
 593 594 595 597 608 610 613 616 619 622 624 625 627 631 633 634 635 636
 647 651 653 654 659 660 662 665 675 678 680 682]
[  0   2   3   4   5   7  13  16  20  22  26  30  38  39  46  51  54  56
 

In [79]:
df.iloc[1]

X1        5
X2        4
X3        4
X4        5
X5        7
X6       10
X7        3
X8        2
X9        1
label     1
Name: 1, dtype: int64

In [80]:
df

X1  X2  X3  X4  X5  X6  X7  X8  X9  label
0     5   1   1   1   2   1   3   1   1      1
1     5   4   4   5   7  10   3   2   1      1
2     3   1   1   1   2   2   3   1   1      1
3     6   8   8   1   3   4   3   7   1      1
4     4   1   1   3   2   1   3   1   1      1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
678   3   1   1   1   3   2   1   1   1      1
679   2   1   1   1   2   1   1   1   1      1
680   5  10  10   3   7   3   8  10   2      2
681   4   8   6   4   3   4  10   6   1      2
682   4   8   8   5   4   5  10   4   1      2

[683 rows x 10 columns]

In [81]:
v

array([  9,  11,  19,  23,  24,  25,  27,  28,  29,  32,  33,  35,  36,
        41,  42,  43,  44,  47,  53,  57,  58,  61,  67,  70,  72,  73,
        80,  82,  84,  86,  87,  88,  91,  94,  95,  98,  99, 110, 111,
       115, 117, 119, 121, 123, 128, 129, 130, 131, 133, 136, 138, 139,
       143, 147, 148, 149, 151, 152, 166, 168, 169, 174, 177, 180, 182,
       183, 184, 189, 192, 197, 199, 201, 203, 207, 209, 212, 216, 217,
       218, 226, 227, 228, 232, 234, 244, 248, 254, 255, 256, 257, 259,
       260, 265, 269, 273, 274, 275, 277, 280, 286, 287, 288, 290, 291,
       292, 295, 296, 297, 302, 305, 307, 314, 321, 323, 324, 326, 328,
       335, 341, 347, 349, 353, 359, 364, 368, 370, 371, 372, 373, 376,
       377, 381, 382, 383, 387, 388, 393, 394, 396, 398, 407, 410, 411,
       418, 421, 423, 429, 430, 431, 434, 437, 438, 442, 444, 445, 446,
       448, 450, 459, 461, 464, 469, 472, 483, 486, 488, 507, 509, 510,
       512, 515, 520, 522, 525, 526, 528, 536, 537, 543, 544, 54

In [84]:
v[0]

9

In [85]:
len(v)

227

In [88]:
test_fold = [0 for i in range(df.shape[0])]
print(test_fold)
cnt = 0
for t,v in kf.split(df):
    print(v)
    for i in range(len(v)):
        test_fold[v[i]]=cnt
    cnt += 1

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [90]:
print(test_fold)

[1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 0, 2, 0, 1, 0, 0, 1, 0, 0, 2, 1, 0, 1, 2, 2, 2, 1, 2, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 1, 2, 0, 0, 0, 1, 0, 2, 1, 0, 1, 2, 2, 1, 1, 2, 0, 1, 0, 1, 0, 2, 0, 1, 2, 0, 2, 2, 1, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 0, 2, 2, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 2, 2, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 2, 1, 0, 1, 2, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 2, 2, 2, 2, 0, 2, 1, 1, 2, 1, 2, 2, 0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 2, 1, 2, 2, 0, 1, 1, 0, 2, 0, 1, 2, 0, 1, 2, 0, 2, 2, 2, 1, 1, 0, 0, 2, 0, 1, 2, 0, 0, 1, 0, 2, 1, 2, 0, 2, 0, 2, 0, 0, 1, 2, 1, 2, 0, 1, 2, 1, 0, 0, 2, 2, 2, 1, 1, 1, 0, 1, 1, 1, 2, 2, 2, 1, 0, 0, 2, 0, 2, 0, 0, 1, 1, 0, 0, 1, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 2, 2, 0, 1, 0, 1, 2, 0, 0, 0, 2, 1, 0, 1, 2, 2, 2, 1, 2, 0, 0, 2, 1, 1, 0, 1, 0, 2, 2, 2, 1, 2, 2, 2, 0, 0, 2, 2, 2, 1, 0, 1, 0, 2, 0, 1, 2, 0, 2, 1, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 2, 2, 0, 2, 0, 2, 1, 0, 1, 0, 

In [91]:
df

X1  X2  X3  X4  X5  X6  X7  X8  X9  label
0     5   1   1   1   2   1   3   1   1      1
1     5   4   4   5   7  10   3   2   1      1
2     3   1   1   1   2   2   3   1   1      1
3     6   8   8   1   3   4   3   7   1      1
4     4   1   1   3   2   1   3   1   1      1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
678   3   1   1   1   3   2   1   1   1      1
679   2   1   1   1   2   1   1   1   1      1
680   5  10  10   3   7   3   8  10   2      2
681   4   8   6   4   3   4  10   6   1      2
682   4   8   8   5   4   5  10   4   1      2

[683 rows x 10 columns]